### ISSUE TITLE
StoryboardDecoder fails to parse beatmap 51142

### ISSUE THREAD

**Issue by Piotrekol** [mrflashstudio/OsuParsers#20]
https://osu.ppy.sh/beatmapsets/51142#osu/156919
expected string: `LoopOnсe` (parses correctly, 9 bytes)
actual string in that osb: `LoopOnce` (throws, 8 bytes)

Stack trace:
```
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at OsuParsers.Decoders.StoryboardDecoder.ParseSbObject(String line)
   at OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines)
   at OsuParsers.Decoders.StoryboardDecoder.Decode(String path)
```

**Comment by mrflashstudio** [comment]
Thanks for this report! For some reason this was a cyrillic 'с' and not latin 'c'. Fixed in 8f6fd22
