### ISSUE TITLE
Beatmaps with no HitObjects fail to parse

### ISSUE THREAD

**Issue by Piotrekol** [mrflashstudio/OsuParsers#21]
In this specific case this was result of trying to load .osu file with no content(0 lines)

Stack trace:
```
System.InvalidOperationException: 'Sequence contains no elements.'
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines)
   at OsuParsers.Decoders.BeatmapDecoder.Decode(String path)
```

**Comment by mrflashstudio** [comment]
Should be fixed in bf21431
