### ISSUE TITLE
problem with Beatmap.Write

### ISSUE THREAD

**Issue by Redageddon** [mrflashstudio/OsuParsers#32]
after i created a new beatmap and filled it with files i  did a .write and got a System.NullReferenceException: Object reference not set to an instance of an object. Even though it is set to the object i just created. the rest of the error is 
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OsuParsers.Writers.BeatmapWriter.EventsSection(BeatmapEventsSection section)
   at OsuParsers.Writers.BeatmapWriter.Write(Beatmap beatmap)
   at OsuParsers.Beatmaps.Beatmap.Write(String path)
```

**Comment by Redageddon** [comment]
```cs
            Beatmap defaultBeatmap = new Beatmap
            {
                GeneralSection = new BeatmapGeneralSection
                {
                    AudioFilename = intralismBeatMap.MusicFile,
                    AudioLeadIn = 0,
                    PreviewTime = (int)TimeSpan.FromSeconds(intralismBeatMap.MusicTime).TotalMilliseconds / 2,
                    Countdown = false,
                    SampleSet = SampleSet.Normal,
                    StackLeniency = 0.7,
                    Mode = Ruleset.Mania,
                    LetterboxInBreaks = false,
                    SpecialStyle = false,
                    WidescreenStoryboard = false,
                },
                EditorSection = new BeatmapEditorSection
                {
                    DistanceSpacing = 1,
                    BeatDivisor = 4,
                    GridSize = 4,
                    TimelineZoom = 2.4f,
                },
                MetadataSection = new BeatmapMetadataSection
                {
                    Title = intralismBeatMap.Name,
                    TitleUnicode = intralismBeatMap.Name,
                    Artist = intralismBeatMap.GetArtist(),
                    ArtistUnicode = intralismBeatMap.GetArtist(),
                    Creator = "IntralismToolCollection",
                    Version = "IntralismConvert",
                    Source = "Intralism",
                    Tags = new string[0],
                    BeatmapID = 0,
                    BeatmapSetID = 0,
                },
                DifficultySection = new BeatmapDifficultySection
                {
                    HPDrainRate = 5,
                    CircleSize = 4,
                    OverallDifficulty = 5,
                    ApproachRate = 5,
                    SliderMultiplier = 1.4,
                    SliderTickRate = 1,
                },
                EventsSection = new BeatmapEventsSection
                {
                    BackgroundImage = intralismBeatMap.IconFile,
                },
                TimingPoints = new List<TimingPoint>
                {
                    new TimingPoint
                    {
                        Offset = 0,
                        BeatLength = 500,
                        TimeSignature = TimeSignature.SimpleQuadruple,
                        SampleSet = SampleSet.Normal,
                        CustomSampleSet = 0,
                        Volume = 100,
                        Inherited = true,
                        Effects = 0,
                    },
                },
                HitObjects = GetManiaHitObjects(intralismBeatMap.GetSpawnObjects()).ToList(),
            };
            defaultBeatmap.Write("Test.txt");
```

**Comment by mrflashstudio** [comment]
Hey! Sorry for the long response.
This happens because `Storyboard` field of `EventsSection` is null. Add empty `Storyboard` to your `EventsSection` for the time being, i'll fix this in the next update.

Your EventsSection should look like this:
```cs
EventsSection = new BeatmapEventsSection
{
    BackgroundImage = "intralismBeatMap.IconFile",
    Storyboard = new Storyboard()
},
```
